### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by piet0024** [gctools-outilsgc/directory-fe#114]
Update the readme with installation instructions through Docker, Explain eco system, how app works etc.

**Comment by Phanoix** [comment]
For the most part the react app can still be spun up for dev the usual way with npm or yarn start, the main difference is how the connections to notification and profile services work (through environment variables or defaults in start.js). The main new section to be added is for using the big docker-compose file to spin up all the back-end services to create a completely independent fresh dev install (tl;dr  cd docker-e2e; docker-compose up).
