### ISSUE TITLE
Look into issues with safari browser (and safari mobile)

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/directory-fe#122]
just do a round of testing on safari to see if there are any major problems such as being reported in the testing

**Comment by ethanWallace** [comment]
Running off my ipad, noticed an issue when directory hits exactly 768px wide. Causes both desktop and mobile elements to appear. Not caused by Safari but something worth fixing.

**Comment by marc-donofrio** [comment]
On iPhone and iPad it looks good in both portrait and landscape with only 1 button element out of place:![E17DDDEE-5CD2-411E-A258-2DA78AAE2D43.png](https://zube.io/files/tbs-sct/b6e972cd1788adfc4edf5120b8e729b3-e17dddee-5cd2-411e-a258-2da78aae2d43.png)![283B8F56-67CA-424F-A5F3-9DE84FD45BBC.png](https://zube.io/files/tbs-sct/29a5811d831a8f3d2d9a549bda8acc1b-283b8f56-67ca-424f-a5f3-9de84fd45bbc.png)

**Comment by marc-donofrio** [comment]
Ethan: Can you add my marc.donofrio@tbs-sct.gc.ca address to test further?
