### ISSUE TITLE
prep work to add directory icon to account / global nav

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/directory-fe#125]
also why is account not in global nav. just thinking out loud

**Comment by piet0024** [comment]
SVG Icon:
![directory_icon.svg](https://zube.io/files/tbs-sct/0a4a2a58e005f0e739fcdc0ac88de86b-directory_icon.svg)

**Comment by Troy-Lawson** [comment]
I feel like it is off center vertically. Probably wouldn't be noticeable when it is favicon size
