### ISSUE TITLE
Error with Orgchart (I think) when loading profile

### ISSUE THREAD

**Issue by piet0024** [gctools-outilsgc/directory-fe#21]
I visit my profile (/p/22) and I sometimes I receive this error:
![error_i_got](https://user-images.githubusercontent.com/7603237/54379363-a2e0f500-465f-11e9-8934-447b1027b955.jpg)

refreshing the page has a chance to avoid this error, not quite sure how to consistently replicate.

EDIT 

on a page refresh I encountered this error: 
![error_i_got2](https://user-images.githubusercontent.com/7603237/54385568-4d134980-466d-11e9-8617-69637d950ac3.jpg)

**Comment by lucbelliveau** [comment]
I noticed this while working on another feature and fixed it - can you test again?

**Comment by piet0024** [comment]
Tested and I haven't re-encountered this issue. I'll close it for now, if it happens again I'll reopen and update this issue.
