### ISSUE TITLE
Error user is not part of a department and organization

### ISSUE THREAD

**Issue by Steph4104** [gctools-outilsgc/directory-fe#34]
![image](https://user-images.githubusercontent.com/15112568/54942970-a8172d00-4f06-11e9-9372-aff7590c7896.png)

![image](https://user-images.githubusercontent.com/15112568/54942985-af3e3b00-4f06-11e9-9447-8d298792dbb6.png)

**Comment by bryan-robitaille** [comment]
This error should disappear once the dummy data is updated.  A change was done where every new user is automatically given a default organization and team.  When the dummy data was created that feature was not yet implemented.  A dummy data refresh should fix this issue.
Leaving it open for now until we can confirm a dummy data refresh fixes the issue

**Comment by piet0024** [comment]
It appears the dummy data refresh has fixed this issue.
